/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file test_dummy_mod.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 2.1
 * 
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */

/* USER CODE FILE INTRODUCTION END */

#include "test_dummy_mod.h"
#include "oe_kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */
#include "../../oe_test.h"
/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_TestDummy_t *TestDummy;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: TestDummy.
 * 
 * @param Args A pointer to the init params for the module.
 * @return OE_Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
static inline OE_Error_t init_TestDummy(void *Args);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle the request: Dummy_Request_1.
 * 
 * The TestDummy subscribes this request in order to test the OpenEDOS core.
 * 
 * @param Header Pointer to the header of the request message.
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Dummy_Request_1(
	OE_MessageHeader_t *Header,
	struct requestArgs_Dummy_Request_1_s *Args);

/**
 * @brief Handle the request: Kernel_Start.
 * 
 * Test the system request functionality.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args);

/**
 * @brief Handle the request: Dummy_Request_2.
 * 
 * The TestDummy subscribes this request in order to test the OpenEDOS core.
 */
static void handleRequest_Dummy_Request_2(void);

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle a response to the request: Dummy_Request_1.
 * 
 * @param Args Pointer to the response parameters.
 */
static void handleResponse_Dummy_Request_1(
	OE_MessageHeader_t *Header,
	struct responseArgs_Dummy_Request_1_s *Args);

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Initialize the module and register handlers. */
OE_Error_t initModule_TestDummy(
    module_TestDummy_t *pTestDummy,
    void *Args,
    OE_Kernel_t *Kernel)
{
    OE_Error_t Error;
    
    /* List the requests this module will handle. */
    OE_RequestID_t RequestIDs[] = {
		RID_Dummy_Request_1,
		RID_Kernel_Start,
		RID_Dummy_Request_2,
	};

    /* List the request handlers accordingly. */
    OE_MessageHandler_t RequestHandlers[] = {
		(OE_MessageHandler_t)handleRequest_Dummy_Request_1,
		(OE_MessageHandler_t)handleRequest_Kernel_Start,
		(OE_MessageHandler_t)handleRequest_Dummy_Request_2,
	};

    /* Setup the module connections. */
    TestDummy = pTestDummy;
    TestDummy->Kernel = Kernel;

    /* Register the request handlers. */
    Error = OE_Kernel_registerHandlers(
        Kernel,
        RequestIDs,
        RequestHandlers,
        sizeof(RequestIDs)/sizeof(OE_RequestID_t));

    if (Error == OE_ERROR_NONE)
    {
        /* Initialize the module. */
        Error = init_TestDummy(Args);
    }

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        /* Unregister handlers if an error occured. */
        OE_Kernel_unregisterHandlers(
            Kernel,
            RequestIDs,
            RequestHandlers,
            sizeof(RequestIDs)/sizeof(OE_RequestID_t));
        
        TestDummy->Kernel = NULL;
        TestDummy = NULL;  

        return Error; 
    }

    /* Nice, we're done here. */
    return OE_ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t init_TestDummy(void *Args)
{
    /* USER CODE MODULE INIT BEGIN */
	TestParam_1 = TEST_VAL_MODULE_INIT;
    TestParam_2 = TEST_VAL_MODULE_INIT;
    TestParam_3 = TEST_VAL_MODULE_INIT;
	
	/* Return no error if everything is fine. */
	return OE_ERROR_NONE;
    /* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

void handleRequest_Dummy_Request_1(
	OE_MessageHeader_t *Header,
	struct requestArgs_Dummy_Request_1_s *Args)
{
    /* USER CODE REQUEST DUMMY REQUEST 1 BEGIN */
	TestParam_1 = Args->Dummy_Request_Param_1;
	TestParam_2 = Args->Dummy_Request_Param_2;

	res_Dummy_Request_1(
		TEST_VAL_3, 
		Header);
    /* USER CODE REQUEST DUMMY REQUEST 1 END */
}

void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args)
{
    /* USER CODE REQUEST KERNEL START BEGIN */
	TestParam_1 = TEST_VAL_KERNEL_START;
    TestParam_2 = TEST_VAL_KERNEL_START;
    TestParam_3 = TEST_VAL_KERNEL_START;
    /* USER CODE REQUEST KERNEL START END */
}

void handleRequest_Dummy_Request_2(void)
{
    /* USER CODE REQUEST DUMMY REQUEST 2 BEGIN */

    /* USER CODE REQUEST DUMMY REQUEST 2 END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

void handleResponse_Dummy_Request_1(
	OE_MessageHeader_t *Header,
	struct responseArgs_Dummy_Request_1_s *Args)
{
    /* USER CODE RESPONSE DUMMY REQUEST 1 BEGIN */
	TestParam_3 = Args->Dummy_Response_Param_1;
    /* USER CODE RESPONSE DUMMY REQUEST 1 END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */
OE_Error_t subscribeRequest_1(void)
{
	OE_RequestID_t RequestID = RID_Dummy_Request_1;
	OE_MessageHandler_t RequestHandler = handleRequest_Dummy_Request_1;

	/* Register the request handler. */
	return OE_Kernel_registerHandlers(
		TestDummy->Kernel,
		&RequestID,
		&RequestHandler,
		1);
}

void unsubscribeRequest_1(void)
{
	OE_RequestID_t RequestID = RID_Dummy_Request_1;
	OE_MessageHandler_t RequestHandler = handleRequest_Dummy_Request_1;

	/* Unregister the request handler. */
	OE_Kernel_unregisterHandlers(
		TestDummy->Kernel,
		&RequestID,
		&RequestHandler,
		1);
}

OE_Error_t sendRequest_1(void)
{
	return req_Dummy_Request_1(
		TEST_VAL_1,
		TEST_VAL_2,
		handleResponse_Dummy_Request_1,
		TestDummy->Kernel->KernelID);
}

OE_Error_t subscribeRequest_2(void)
{
	OE_RequestID_t RequestID = RID_Dummy_Request_2;
	OE_MessageHandler_t RequestHandler = handleRequest_Dummy_Request_2;

	/* Register the request handler. */
	return OE_Kernel_registerHandlers(
		TestDummy->Kernel,
		&RequestID,
		&RequestHandler,
		1);
}

void unsubscribeRequest_2(void)
{
	OE_RequestID_t RequestID = RID_Dummy_Request_2;
	OE_MessageHandler_t RequestHandler = handleRequest_Dummy_Request_2;

	/* Unregister the request handler. */
	OE_Kernel_unregisterHandlers(
		TestDummy->Kernel,
		&RequestID,
		&RequestHandler,
		1);
}

OE_Error_t sendRequest_2(void)
{
	return req_Dummy_Request_2();
}
/* USER CODE MODULE FUNCTIONS END */

