/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file test_dummy_intf.h
 * @author Samu
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 2.1
 * 
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */

/* USER CODE FILE INTRODUCTION END */

#ifndef TEST_DUMMY_INTF_H
#define TEST_DUMMY_INTF_H

#include "oe_defines.h"

/* Includes, defines, typedefs, etc. */
/* USER CODE INTERFACE HEADER BEGIN */

/* USER CODE INTERFACE HEADER END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* Dummy_Request_1 */

/**
 * @brief Send a message to request: Dummy_Request_1.
 * 
 * This request is used to test the OpenEDOS core.
 * Response: Yes
 * 
 * @param Dummy_Request_Param_1 A dummy parameter for testing.
 * @param Dummy_Request_Param_2 A dummy parameter for testing.
 * @param ResponseHandler A pointer to the function
 * that will handle the response to this request.
 * 
 * @param KernelID The ID of the kernel to which
 * the requesting module belongs.
 * 
 * @return OE_Error_t An error is returned if
 * - processing the message results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
OE_Error_t req_Dummy_Request_1(
	uint8_t Dummy_Request_Param_1,
	uint8_t Dummy_Request_Param_2,
	OE_MessageHandler_t ResponseHandler,
	OE_KernelID_t KernelID);

struct requestArgs_Dummy_Request_1_s {
	uint8_t Dummy_Request_Param_1;
	uint8_t Dummy_Request_Param_2;
};

/**
 * @brief Send a response to the request: Dummy_Request_1.
 * 
 * The response is used to test the OpenEDOS core.
 * 
 * @param Dummy_Response_Param_1 A dummy parameter for testing.
 * @param RequestHeader A pointer to the header of
 * the request message to which this response is sent.
 * @return OE_Error_t An error is returned if
 * - processing the message results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
OE_Error_t res_Dummy_Request_1(
	uint8_t Dummy_Response_Param_1,
	OE_MessageHeader_t* RequestHeader);

struct responseArgs_Dummy_Request_1_s {
	uint8_t Dummy_Response_Param_1;
};

/* Dummy_Request_2 */

/**
 * @brief Send a message to request: Dummy_Request_2.
 * 
 * This request is used to test the OpenEDOS core.
 * Response: No
 * 
 * @return OE_Error_t An error is returned if
 * - processing the message results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
OE_Error_t req_Dummy_Request_2(void);

#endif // TEST_DUMMY_INTF_H