/**
 * @note This file was autogenerated with OpenEDOS v2.2.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file oe_all_modules.h
 * @author OpenEDOS Systembuilder
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * (c) 2025 Samuel Ardaya-Lieb, MIT license
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#ifndef OE_ALL_MODULES_H
#define OE_ALL_MODULES_H

#include "timer_mod.h"
#include "printer_mod.h"

#endif // OE_ALL_MODULES_H