/**
 * Created with the OpenEDOS SystemBuilder v0.1.
 * Created for the OpenEDOS Core v0.2.1.
 * 
 * This file is autogenerated. Sections inside USER CODE BEGIN and USER CODE END
 * will be left untouched when rerunning the code generation. Happy coding!
 * 
 * @file system_requests_intf.c
 * @author Samuel Ardaya-Lieb
 * @version 
 * @date 2024-07-17
 * 
 * 
 */

/* USER CODE FILE HEADER BEGIN */

/* USER CODE FILE HEADER END */

#include "system_requests_intf.h"
#include "kernel_switch.h"

/* Includes, typedefs, globals, etc. */
/* USER CODE INTERFACE GLOBALS BEGIN */
#if USE_SYSTEM_REQUESTS
/* USER CODE INTERFACE GLOBALS END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

Error_t req_Kernel_Start(
	KernelID_t KernelID)
{
	MessageHeader_t MessageHeader = {
		.RequestID = RID_Kernel_Start,
	};

	return KernelSwitch_sendRequest(
		&MessageHeader,
		&(struct requestArgs_Kernel_Start_s){
			KernelID,
		});
}

Error_t req_Kernel_Stop(
	KernelID_t KernelID)
{
	MessageHeader_t MessageHeader = {
		.RequestID = RID_Kernel_Stop,
	};

	return KernelSwitch_sendRequest(
		&MessageHeader,
		&(struct requestArgs_Kernel_Stop_s){
			KernelID,
		});
}


/* Something else...? */
/* USER CODE INTERFACE SOURCE BEGIN */
#endif
/* USER CODE INTERFACE SOURCE END */
