/**
 * @note This file was autogenerated with OpenEDOS v2.0.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file multi_kernel_test_dummy_1_intf.c
 * @author Samu
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 2.0
 * 
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE HEADER BEGIN */

/* USER CODE FILE HEADER END */

#include "multi_kernel_test_dummy_1_intf.h"
#include "oe_core_mod.h"

/* Includes, typedefs, globals, etc. */
/* USER CODE INTERFACE GLOBALS BEGIN */

/* USER CODE INTERFACE GLOBALS END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* There are no requests associated with this interface. */


/* Something else...? */
/* USER CODE INTERFACE SOURCE BEGIN */

/* USER CODE INTERFACE SOURCE END */
