/**
 * @note This file was autogenerated with OpenEDOS v2.0.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file multi_kernel_test_dummy_1_intf.h
 * @author Samu
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 2.0
 * 
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE HEADER BEGIN */

/* USER CODE FILE HEADER END */

#ifndef MULTI_KERNEL_TEST_DUMMY_1_INTF_H
#define MULTI_KERNEL_TEST_DUMMY_1_INTF_H

#include "oe_defines.h"

/* Includes, defines, typedefs, etc. */
/* USER CODE INTERFACE HEADER BEGIN */

/* USER CODE INTERFACE HEADER END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* There are no requests associated with this module. */

#endif // MULTI_KERNEL_TEST_DUMMY_1_INTF_H