/**
 * @note This file was autogenerated with OpenEDOS v2.0.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file multi_kernel_test_dummy_1_mod.c
 * @author Samu
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 2.0
 * 
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE HEADER BEGIN */

/* USER CODE FILE HEADER END */

#include "multi_kernel_test_dummy_1_mod.h"
#include "oe_kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */

/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_multiKernel_TestDummy_1_t *multiKernel_TestDummy_1;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: multiKernel_TestDummy_1.
 * 
 * @param Args A pointer to the init params for the module.
 * 
 * @return OE_Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
static inline OE_Error_t init_multiKernel_TestDummy_1(void *Args);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any request handlers. */

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Initialize the module and register handlers. */
OE_Error_t initModule_multiKernel_TestDummy_1(
    module_multiKernel_TestDummy_1_t *pmultiKernel_TestDummy_1,
    void *Args,
    OE_Kernel_t *Kernel)
{
    OE_Error_t Error;
    
    /* List the requests this module will handle. */
    OE_RequestID_t RequestIDs[] = {
	};

    /* List the request handlers accordingly. */
    OE_MessageHandler_t RequestHandlers[] = {
	};

    /* Setup the module connections. */
    multiKernel_TestDummy_1 = pmultiKernel_TestDummy_1;
    multiKernel_TestDummy_1->Kernel = Kernel;

    /* Initialize the module. */
    Error = init_multiKernel_TestDummy_1(Args);

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        multiKernel_TestDummy_1->Kernel = NULL;
        multiKernel_TestDummy_1 = NULL;
        
        return Error;
    }

    /* Register the request handlers. */
    Error = OE_Kernel_registerHandlers(
        Kernel,
        RequestIDs,
        RequestHandlers,
        sizeof(RequestIDs)/sizeof(OE_RequestID_t));

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        /* Unregister handlers if an error occured. */
        OE_Kernel_unregisterHandlers(
            Kernel,
            RequestIDs,
            RequestHandlers,
            sizeof(RequestIDs)/sizeof(OE_RequestID_t));
        
        multiKernel_TestDummy_1->Kernel = NULL;
        multiKernel_TestDummy_1 = NULL;  

        return Error; 
    }

    /* Nice, we're done here. */
    return OE_ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t init_multiKernel_TestDummy_1(void *Args)
{
	/* USER CODE MODULE INIT BEGIN */
/* Avoid unused warning. */
(void)Args;


	/* Return no error if everything is fine. */
	return OE_ERROR_NONE;
	/* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any request handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */

/* USER CODE MODULE FUNCTIONS END */

