/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file dummy_2_mod.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#include "dummy_2_mod.h"
#include "oe_kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */
/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_Dummy_2_t *Dummy_2;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: Dummy_2.
 * 
 * @param Args A pointer to the init params for the module.
 * @return OE_Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
static inline OE_Error_t init_Dummy_2(void *Args);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle the request: Kernel_Start.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args);

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Initialize the module and register handlers. */
OE_Error_t initModule_Dummy_2(
    module_Dummy_2_t *pDummy_2,
    void *Args,
    OE_Kernel_t *Kernel)
{
    OE_Error_t Error;
    
    /* List the requests this module will handle. */
    OE_RequestID_t RequestIDs[] = {
		RID_Kernel_Start,
	};

    /* List the request handlers accordingly. */
    OE_MessageHandler_t RequestHandlers[] = {
		(OE_MessageHandler_t)handleRequest_Kernel_Start,
	};

    /* Setup the module connections. */
    Dummy_2 = pDummy_2;
    Dummy_2->Kernel = Kernel;

    /* Register the request handlers. */
    Error = OE_Kernel_registerHandlers(
        Kernel,
        RequestIDs,
        RequestHandlers,
        sizeof(RequestIDs)/sizeof(OE_RequestID_t));

    if (Error == OE_ERROR_NONE)
    {
        /* Initialize the module. */
        Error = init_Dummy_2(Args);
    }

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        /* Unregister handlers if an error occured. */
        OE_Kernel_unregisterHandlers(
            Kernel,
            RequestIDs,
            RequestHandlers,
            sizeof(RequestIDs)/sizeof(OE_RequestID_t));
        
        Dummy_2->Kernel = NULL;
        Dummy_2 = NULL;  

        return Error; 
    }

    /* Nice, we're done here. */
    return OE_ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t init_Dummy_2(void *Args)
{
    /* USER CODE MODULE INIT BEGIN */
	/* Avoid unused warning. */
	(void)Args;


	/* Return no error if everything is fine. */
	return OE_ERROR_NONE;
    /* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args)
{
    /* USER CODE REQUEST KERNEL START BEGIN */
    /* USER CODE REQUEST KERNEL START END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */
/* USER CODE MODULE FUNCTIONS END */

