/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file dummy_2_intf.h
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#ifndef DUMMY_2_INTF_H
#define DUMMY_2_INTF_H

#include "oe_defines.h"

/* Includes, defines, typedefs, etc. */
/* USER CODE INTERFACE HEADER BEGIN */
/* USER CODE INTERFACE HEADER END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* There are no requests associated with this module. */

#endif // DUMMY_2_INTF_H