/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file timer_intf.h
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 1.0
 * 
 * (c) 2024 Samuel Ardaya-Lieb, MIT license
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */

/* USER CODE FILE INTRODUCTION END */

#ifndef TIMER_INTF_H
#define TIMER_INTF_H

#include "oe_defines.h"

/* Includes, defines, typedefs, etc. */
/* USER CODE INTERFACE HEADER BEGIN */

/* USER CODE INTERFACE HEADER END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* Tick */

/**
 * @brief Send a message to request: Tick.
 * 
 * The periodic timer tick.
 * Response: No
 * 
 * @return OE_Error_t An error is returned if
 * - processing the message results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
OE_Error_t req_Tick(void);

#endif // TIMER_INTF_H