/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file timer_intf.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 1.0
 * 
 * (c) 2024 Samuel Ardaya-Lieb, MIT license
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */

/* USER CODE FILE INTRODUCTION END */

#include "timer_intf.h"
#include "oe_core_mod.h"

/* Includes, typedefs, globals, etc. */
/* USER CODE INTERFACE GLOBALS BEGIN */

/* USER CODE INTERFACE GLOBALS END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t req_Tick(void)
{
	OE_MessageHeader_t MessageHeader = {
		.RequestID = RID_Tick,
	};

	return OE_Core_sendRequest(
		&MessageHeader,
		NULL);
}

/* Something else...? */
/* USER CODE INTERFACE SOURCE BEGIN */

/* USER CODE INTERFACE SOURCE END */
