/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file timer_mod.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * @version 1.0
 * 
 * (c) 2025 Samuel Ardaya-Lieb, MIT license
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */

/* USER CODE FILE INTRODUCTION END */

#include "timer_mod.h"
#include "oe_kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */
#include <unistd.h>
/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_Timer_t *Timer;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: Timer.
 * 
 * @param Args A pointer to the init params for the module.
 * 
 * @return OE_Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
static inline OE_Error_t init_Timer(void *Args);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle the request: Kernel_Start.
 * 
 * Start the timer initially.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args);

/**
 * @brief Handle the request: Tick.
 * 
 * Restart the timer.
 */
static void handleRequest_Tick(void);

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Initialize the module and register handlers. */
OE_Error_t initModule_Timer(
    module_Timer_t *pTimer,
    void *Args,
    OE_Kernel_t *Kernel)
{
    OE_Error_t Error;
    
    /* List the requests this module will handle. */
    OE_RequestID_t RequestIDs[] = {
		RID_Kernel_Start,
		RID_Tick,
	};

    /* List the request handlers accordingly. */
    OE_MessageHandler_t RequestHandlers[] = {
		(OE_MessageHandler_t)handleRequest_Kernel_Start,
		(OE_MessageHandler_t)handleRequest_Tick,
	};

    /* Setup the module connections. */
    Timer = pTimer;
    Timer->Kernel = Kernel;

    /* Initialize the module. */
    Error = init_Timer(Args);

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        Timer->Kernel = NULL;
        Timer = NULL;
        
        return Error;
    }

    /* Register the request handlers. */
    Error = OE_Kernel_registerHandlers(
        Kernel,
        RequestIDs,
        RequestHandlers,
        sizeof(RequestIDs)/sizeof(OE_RequestID_t));

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        /* Unregister handlers if an error occured. */
        OE_Kernel_unregisterHandlers(
            Kernel,
            RequestIDs,
            RequestHandlers,
            sizeof(RequestIDs)/sizeof(OE_RequestID_t));
        
        Timer->Kernel = NULL;
        Timer = NULL;  

        return Error; 
    }

    /* Nice, we're done here. */
    return OE_ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t init_Timer(void *Args)
{
	/* USER CODE MODULE INIT BEGIN */
	/* Avoid unused warning. */
	(void)Args;


	/* Return no error if everything is fine. */
	return OE_ERROR_NONE;
	/* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * Start the timer initially.
 */
void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args)
{
	/* USER CODE REQUEST KERNEL START BEGIN */
    req_Tick();
	/* USER CODE REQUEST KERNEL START END */
}

/**
 * Restart the timer.
 */
void handleRequest_Tick(void)
{
	/* USER CODE REQUEST TICK BEGIN */
    sleep(1);
    req_Tick();
	/* USER CODE REQUEST TICK END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */

/* USER CODE MODULE FUNCTIONS END */

