/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file dummy_1_intf.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#include "dummy_1_intf.h"
#include "oe_core_mod.h"

/* Includes, typedefs, globals, etc. */
/* USER CODE INTERFACE GLOBALS BEGIN */
/* USER CODE INTERFACE GLOBALS END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* There are no requests associated with this interface. */

/* Something else...? */
/* USER CODE INTERFACE SOURCE BEGIN */
/* USER CODE INTERFACE SOURCE END */
