/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file dummy_1_mod.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2025 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#include "dummy_1_mod.h"
#include "oe_kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */
/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_Dummy_1_t *Dummy_1;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: Dummy_1.
 * 
 * @param Args A pointer to the init params for the module.
 * @return OE_Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
static inline OE_Error_t init_Dummy_1(void *Args);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle the request: Kernel_Start.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args);

/**
 * @brief Handle the request: Test_End.
 */
static void handleRequest_Test_End(void);

/**
 * @brief Handle the request: Dummy_1_Req.
 */
static void handleRequest_Dummy_1_Req(void);

/**
 * @brief Handle the request: Dummy_1_toggleRegistration.
 */
static void handleRequest_Dummy_1_toggleRegistration(void);

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Initialize the module and register handlers. */
OE_Error_t initModule_Dummy_1(
    module_Dummy_1_t *pDummy_1,
    void *Args,
    OE_Kernel_t *Kernel)
{
    OE_Error_t Error;
    
    /* List the requests this module will handle. */
    OE_RequestID_t RequestIDs[] = {
		RID_Kernel_Start,
		RID_Test_End,
		RID_Dummy_1_Req,
		RID_Dummy_1_toggleRegistration,
	};

    /* List the request handlers accordingly. */
    OE_MessageHandler_t RequestHandlers[] = {
		(OE_MessageHandler_t)handleRequest_Kernel_Start,
		(OE_MessageHandler_t)handleRequest_Test_End,
		(OE_MessageHandler_t)handleRequest_Dummy_1_Req,
		(OE_MessageHandler_t)handleRequest_Dummy_1_toggleRegistration,
	};

    /* Setup the module connections. */
    Dummy_1 = pDummy_1;
    Dummy_1->Kernel = Kernel;

    /* Register the request handlers. */
    Error = OE_Kernel_registerHandlers(
        Kernel,
        RequestIDs,
        RequestHandlers,
        sizeof(RequestIDs)/sizeof(OE_RequestID_t));

    if (Error == OE_ERROR_NONE)
    {
        /* Initialize the module. */
        Error = init_Dummy_1(Args);
    }

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        /* Unregister handlers if an error occured. */
        OE_Kernel_unregisterHandlers(
            Kernel,
            RequestIDs,
            RequestHandlers,
            sizeof(RequestIDs)/sizeof(OE_RequestID_t));
        
        Dummy_1->Kernel = NULL;
        Dummy_1 = NULL;  

        return Error; 
    }

    /* Nice, we're done here. */
    return OE_ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t init_Dummy_1(void *Args)
{
    /* USER CODE MODULE INIT BEGIN */
    Dummy_1->handlerRegistered = true;
    Dummy_1->requests = 0;
    Dummy_1->suite = (CuSuite*)Args;
    Dummy_1->tc = Dummy_1->suite->list[0];   
    
    CuAssertIntEquals(Dummy_1->tc, TEST_VAL_TEST_BEGIN, TestParam_1);
    TestParam_1 = TEST_VAL_MODULE_INIT;
	/* Return no error if everything is fine. */
	return OE_ERROR_NONE;
    /* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args)
{
    /* USER CODE REQUEST KERNEL START BEGIN */
    (void)Header;
    if (Args->KernelID == Dummy_1->Kernel->KernelID)
    {
        CuAssertIntEquals(Dummy_1->tc, 1, Dummy_1->Kernel->KernelID);
        CuAssertIntEquals(Dummy_1->tc, TEST_VAL_MODULE_INIT, TestParam_1);
        TestParam_1 = TEST_VAL_KERNEL_START;   
    }
    /* USER CODE REQUEST KERNEL START END */
}

void handleRequest_Test_End(void)
{
    /* USER CODE REQUEST TEST END BEGIN */
    printf("Dummy 1: received %d requests\n", Dummy_1->requests);
    summarizeKernelTests(Dummy_1->suite, Dummy_1->Kernel->KernelID);
    pthread_exit(NULL);
    /* USER CODE REQUEST TEST END END */
}

void handleRequest_Dummy_1_Req(void)
{
    /* USER CODE REQUEST DUMMY 1 REQ BEGIN */
    CuAssertTrue(Dummy_1->tc, Dummy_1->handlerRegistered);
    Dummy_1->requests++;
    unregisterHandler();
    /* USER CODE REQUEST DUMMY 1 REQ END */
}

void handleRequest_Dummy_1_toggleRegistration(void)
{
    /* USER CODE REQUEST DUMMY 1 TOGGLE REGISTRATION BEGIN */
    if (Dummy_1->handlerRegistered)
    {
        unregisterHandler();
    }
    else
    {
        registerHandler();
    }
    /* USER CODE REQUEST DUMMY 1 TOGGLE REGISTRATION END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */
void registerHandler(void)
{
    OE_Error_t Error;
    OE_RequestID_t RID = RID_Dummy_1_Req;
    OE_MessageHandler_t Handler = (OE_MessageHandler_t)handleRequest_Dummy_1_Req;

    Error = OE_Kernel_registerHandlers(
        Dummy_1->Kernel,
        &RID,
        &Handler,
        1);
    CuAssertIntEquals(Dummy_1->tc, OE_ERROR_NONE, Error);
    
    Dummy_1->handlerRegistered = true;
}

void unregisterHandler(void)
{
    OE_RequestID_t RID = RID_Dummy_1_Req;
    OE_MessageHandler_t Handler = (OE_MessageHandler_t)handleRequest_Dummy_1_Req;

    OE_Kernel_unregisterHandlers(
        Dummy_1->Kernel,
        &RID,
        &Handler,
        1);
    Dummy_1->handlerRegistered = false;
}
/* USER CODE MODULE FUNCTIONS END */

