/**
 * @note This file was autogenerated with OpenEDOS v2.2.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file oe_all_modules.h
 * @author OpenEDOS Systembuilder
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2025 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#ifndef OE_ALL_MODULES_H
#define OE_ALL_MODULES_H

#include "dummy_1_mod.h"
#include "dummy_2_mod.h"
#include "dummy_0_mod.h"
#include "test_dummy_mod.h"
#include "oe_core_mod.h"

#endif // OE_ALL_MODULES_H