/**
 * Created with the OpenEDOS SystemBuilder v0.1.
 * Created for the OpenEDOS Core v0.2.1.
 * 
 * This file is autogenerated. Sections inside USER CODE BEGIN and USER CODE END
 * will be left untouched when rerunning the code generation. Happy coding!
 * 
 * @file test_dummy_mod.c
 * @author Samuel Ardaya-Lieb
 * @version 0.0.1
 * @date 2024-07-05
 * 
 * copyright (c) 2024 Samuel Ardaya-Lieb, MIT license
 */

/* USER CODE FILE HEADER BEGIN */

/* USER CODE FILE HEADER END */

#include "test_dummy_mod.h"
#include "kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */
#include "../../AllTests.h"
/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_TestDummy_t *TestDummy;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: TestDummy.
 * 
 * @return Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise ERROR_NONE is returned.
 */
static inline Error_t initTestDummy(void);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle the request: Dummy_Request.
 * 
 * The TestDummy subscribes this request in order to test the OpenEDOS core.
 * 
 * @param Header Pointer to the header of the request message.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Dummy_Request(
	MessageHeader_t *Header,
	struct requestArgs_Dummy_Request_s *Args);

/**
 * @brief Handle the request: System_Start.
 * 
 * Test the system request functionality.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_System_Start(
	MessageHeader_t *Header,
	struct requestArgs_System_Start_s *Args);

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle a response to the request: Dummy_Request.
 * 
 * The TestDummy subscribes this request in order to test the OpenEDOS core.
 * 
 * @param Args Pointer to the response parameters.
 */
static void handleResponse_Dummy_Request(
	MessageHeader_t *Header,
	struct responseArgs_Dummy_Request_s *Args);

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Register handlers and initialize the module. */
Error_t initModule_TestDummy(
	module_TestDummy_t *pTestDummy,
	Kernel_t *Kernel)
{
	/* List the requests this module will handle. */
	RequestID_t RequestIDs[] = {
		RID_Dummy_Request,
		RID_System_Start,
	};

	/* List the request handlers accordingly. */
	MessageHandler_t RequestHandlers[] = {
		(MessageHandler_t)handleRequest_Dummy_Request,
		(MessageHandler_t)handleRequest_System_Start,
	};

	/* Register the request handlers. */
	Error_t Error = Kernel_registerHandlers(
		Kernel,
		RequestIDs,
		RequestHandlers,
		sizeof(RequestIDs)/sizeof(RequestID_t));

	/* Check for errors. */
	if(Error != ERROR_NONE)
	{
		return Error;
	}

	/* Setup the module connections. */
	TestDummy = pTestDummy;
	TestDummy->Kernel = Kernel;

	/* Initialize the module. */
	Error = initTestDummy();

	/* Check for errors. */
	if(Error != ERROR_NONE)
	{
		/* Unregister handlers if an error occured. */
		Kernel_unregisterHandlers(
			Kernel,
			RequestIDs,
			RequestHandlers,
			sizeof(RequestIDs)/sizeof(RequestID_t));

		return Error;
	}

	/* Nice, we're done here. */
	return ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

Error_t initTestDummy(void)
{
	/* USER CODE MODULE INIT BEGIN */
	TestParam_1 = TEST_VAL_MODULE_INIT;
    TestParam_2 = TEST_VAL_MODULE_INIT;
    TestParam_3 = TEST_VAL_MODULE_INIT;

	/* Return no error if everything is fine. */
	return ERROR_NONE;
	/* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * The TestDummy subscribes this request in order to test the OpenEDOS core.
 */
void handleRequest_Dummy_Request(
	MessageHeader_t *Header,
	struct requestArgs_Dummy_Request_s *Args)
{
	/* USER CODE REQUEST DUMMY REQUEST BEGIN */
	TestParam_1 = Args->Dummy_Request_Param_1;
	TestParam_2 = Args->Dummy_Request_Param_2;

	res_Dummy_Request(
		TEST_VAL_3, 
		Header);
	/* USER CODE REQUEST DUMMY REQUEST END */
}

/**
 * Test the system request functionality.
 */
void handleRequest_System_Start(
	MessageHeader_t *Header,
	struct requestArgs_System_Start_s *Args)
{
	/* USER CODE REQUEST SYSTEM START BEGIN */
	TestParam_1 = TEST_VAL_SYSTEM_START;
    TestParam_2 = TEST_VAL_SYSTEM_START;
    TestParam_3 = TEST_VAL_SYSTEM_START;

	req_Dummy_Request(
		TEST_VAL_1,
		TEST_VAL_2,
		handleResponse_Dummy_Request,
		TestDummy->Kernel->KernelID);
	/* USER CODE REQUEST SYSTEM START END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * The TestDummy subscribes this request in order to test the OpenEDOS core.
 */
void handleResponse_Dummy_Request(
	MessageHeader_t *Header,
	struct responseArgs_Dummy_Request_s *Args)
{
	/* USER CODE RESPONSE DUMMY REQUEST BEGIN */
	TestParam_3 = Args->Dummy_Response_Param_1;
	/* USER CODE RESPONSE DUMMY REQUEST END */
}


//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */

/* USER CODE MODULE FUNCTIONS END */

