/**
 * Created with the OpenEDOS SystemBuilder v0.1.
 * Created for the OpenEDOS Core v0.2.1.
 * 
 * This file is autogenerated. Sections inside USER CODE BEGIN and USER CODE END
 * will be left untouched when rerunning the code generation. Happy coding!
 * 
 * @file test_dummy_intf.c
 * @author Samuel Ardaya-Lieb
 * @version 0.0.1
 * @date 2024-07-05
 * 
 * copyright (c) 2024 Samuel Ardaya-Lieb, MIT license
 */

/* USER CODE FILE HEADER BEGIN */

/* USER CODE FILE HEADER END */

#include "test_dummy_intf.h"
#include "kernel_switch.h"

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

Error_t req_Dummy_Request(
	uint8_t Dummy_Request_Param_1,
	uint8_t Dummy_Request_Param_2,
	MessageHandler_t ResponseHandler,
	KernelID_t KernelID)
{
	MessageHeader_t MessageHeader = {
		.RequestID = RID_Dummy_Request,
		.ResponseHandler = ResponseHandler,
		.KernelID = KernelID,
	};

	return KernelSwitch_sendRequest(
		&MessageHeader,
		&(struct requestArgs_Dummy_Request_s){
			Dummy_Request_Param_1,
			Dummy_Request_Param_2,
		});
}


Error_t res_Dummy_Request(
	uint8_t Dummy_Response_Param_1,
	MessageHeader_t* RequestHeader)
{
	return KernelSwitch_sendResponse(
		RequestHeader,
		&(struct responseArgs_Dummy_Request_s){
			Dummy_Response_Param_1,
		});
}


/* Something else...? */
/* USER CODE INTERFACE SOURCE BEGIN */

/* USER CODE INTERFACE SOURCE END */
