/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file dummy_0_intf.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#include "dummy_0_intf.h"
#include "oe_core_mod.h"

/* Includes, typedefs, globals, etc. */
/* USER CODE INTERFACE GLOBALS BEGIN */
/* USER CODE INTERFACE GLOBALS END */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Requests ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t req_Dummy_0_Req(
	uint8_t param,
	CuTest* tc,
	OE_MessageHandler_t ResponseHandler,
	OE_KernelID_t KernelID)
{
	OE_MessageHeader_t MessageHeader = {
		.RequestID = RID_Dummy_0_Req,
		.ResponseHandler = ResponseHandler,
		.KernelID = KernelID,
	};

	return OE_Core_sendRequest(
		&MessageHeader,
		&(struct requestArgs_Dummy_0_Req_s){
			param,
			tc,
		});
}

OE_Error_t res_Dummy_0_Req(
	uint8_t param,
	CuTest* tc,
	OE_MessageHeader_t* RequestHeader)
{
	return OE_Core_sendResponse(
		RequestHeader,
		&(struct responseArgs_Dummy_0_Req_s){
			param,
			tc,
		});
}

/* Something else...? */
/* USER CODE INTERFACE SOURCE BEGIN */
/* USER CODE INTERFACE SOURCE END */
