name: 'Dummy_0'
author: Samuel Ardaya-Lieb
interface:
  create: true
  requests:
  - name: Dummy_0_Req
    description: Send one byte 'param' to Dummy 0.
    request parameters:
    - name: param
      type: uint8_t
    - name: tc
      type: CuTest*
    response: true
    response description: Return the received byte 'param'.
    response parameters:
    - name: param
      type: uint8_t
    - name: tc
      type: CuTest*
module:
  create: true
  kernel: 0
  subscribed requests:
  - name: Kernel_Start
  - name: Dummy_0_Req
  - name: Test_End
  used requests:
  - name: Dummy_0_Req
  - name: Test_End