/**
 * @note This file was autogenerated with OpenEDOS v2.1.
 * Sections inside USER CODE BEGIN and USER CODE END will be left untouched 
 * when rerunning the code generation. Happy coding!
 * 
 * @file dummy_0_mod.c
 * @author Samuel Ardaya-Lieb
 */

/* USER CODE COPYRIGHT NOTICE BEGIN */
/**
 * OpenEDOS, (c) 2022-2024 Samuel Ardaya-Lieb, MIT License
 * 
 * https://github.com/SamuelArdayaLieb/OpenEDOS
 */
/* USER CODE COPYRIGHT NOTICE END */

/* USER CODE FILE INTRODUCTION BEGIN */
/* USER CODE FILE INTRODUCTION END */

#include "dummy_0_mod.h"
#include "oe_kernel.h"

/* Includes, prototypes, globals, etc. */
/* USER CODE MODULE GLOBALS BEGIN */
/* USER CODE MODULE GLOBALS END */

/* Global pointer to the module. */
static module_Dummy_0_t *Dummy_0;

//~~~~~~~~~~~~~~~~~~~~~~~~ Custom init prototype ~~~~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Custom initializer for the module: Dummy_0.
 * 
 * @param Args A pointer to the init params for the module.
 * @return OE_Error_t An error is returned if
 * - initializing the module results in an error.
 * Otherwise OE_ERROR_NONE is returned.
 */
static inline OE_Error_t init_Dummy_0(void *Args);

//~~~~~~~~~~~~~~~~~~~~~~ Request handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/**
 * @brief Handle the request: Kernel_Start.
 * 
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args);

/**
 * @brief Handle the request: Dummy_0_Req.
 * 
 * @param Header Pointer to the header of the request message.
 * @param Args Pointer to the request parameters.
 */
static void handleRequest_Dummy_0_Req(
	OE_MessageHeader_t *Header,
	struct requestArgs_Dummy_0_Req_s *Args);

/**
 * @brief Handle the request: Test_End.
 */
static void handleRequest_Test_End(void);

//~~~~~~~~~~~~~~~~~~~~~ Response handler prototypes ~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~ Module initialization ~~~~~~~~~~~~~~~~~~~~~~~~//

/* Initialize the module and register handlers. */
OE_Error_t initModule_Dummy_0(
    module_Dummy_0_t *pDummy_0,
    void *Args,
    OE_Kernel_t *Kernel)
{
    OE_Error_t Error;
    
    /* List the requests this module will handle. */
    OE_RequestID_t RequestIDs[] = {
		RID_Kernel_Start,
		RID_Dummy_0_Req,
		RID_Test_End,
	};

    /* List the request handlers accordingly. */
    OE_MessageHandler_t RequestHandlers[] = {
		(OE_MessageHandler_t)handleRequest_Kernel_Start,
		(OE_MessageHandler_t)handleRequest_Dummy_0_Req,
		(OE_MessageHandler_t)handleRequest_Test_End,
	};

    /* Setup the module connections. */
    Dummy_0 = pDummy_0;
    Dummy_0->Kernel = Kernel;

    /* Register the request handlers. */
    Error = OE_Kernel_registerHandlers(
        Kernel,
        RequestIDs,
        RequestHandlers,
        sizeof(RequestIDs)/sizeof(OE_RequestID_t));

    if (Error == OE_ERROR_NONE)
    {
        /* Initialize the module. */
        Error = init_Dummy_0(Args);
    }

    /* Check for errors. */
    if (Error != OE_ERROR_NONE)
    {
        /* Unregister handlers if an error occured. */
        OE_Kernel_unregisterHandlers(
            Kernel,
            RequestIDs,
            RequestHandlers,
            sizeof(RequestIDs)/sizeof(OE_RequestID_t));
        
        Dummy_0->Kernel = NULL;
        Dummy_0 = NULL;  

        return Error; 
    }

    /* Nice, we're done here. */
    return OE_ERROR_NONE;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~ Custom init function ~~~~~~~~~~~~~~~~~~~~~~~~//

OE_Error_t init_Dummy_0(void *Args)
{
    /* USER CODE MODULE INIT BEGIN */
    Dummy_0->suite = (CuSuite*)Args;
    Dummy_0->tc = Dummy_0->suite->list[0];

    CuAssertIntEquals(Dummy_0->tc, TEST_VAL_TEST_BEGIN, TestParam_0);
    TestParam_0 = TEST_VAL_MODULE_INIT;
	/* Return no error if everything is fine. */
	return OE_ERROR_NONE;
    /* USER CODE MODULE INIT END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Request handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~~//

void handleRequest_Kernel_Start(
	OE_MessageHeader_t *Header,
	struct requestArgs_Kernel_Start_s *Args)
{
    /* USER CODE REQUEST KERNEL START BEGIN */
    (void)Header;

    if (Args->KernelID == Dummy_0->Kernel->KernelID)
    {
        CuAssertIntEquals(Dummy_0->tc, 0, Dummy_0->Kernel->KernelID); 
        CuAssertIntEquals(Dummy_0->tc, TEST_VAL_MODULE_INIT, TestParam_0);  
        TestParam_0 = TEST_VAL_KERNEL_START;
    }
    /* USER CODE REQUEST KERNEL START END */
}

void handleRequest_Dummy_0_Req(
	OE_MessageHeader_t *Header,
	struct requestArgs_Dummy_0_Req_s *Args)
{
    /* USER CODE REQUEST DUMMY 0 REQ BEGIN */
    OE_Error_t Error;

    Dummy_0->param = Args->param;

    Error = res_Dummy_0_Req(
        Dummy_0->param,
        Header);

    CuAssertIntEquals(Dummy_0->tc, OE_ERROR_NONE, Error);
    /* USER CODE REQUEST DUMMY 0 REQ END */
}

void handleRequest_Test_End(void)
{
    /* USER CODE REQUEST TEST END BEGIN */
    summarizeKernelTests(Dummy_0->suite, Dummy_0->Kernel->KernelID);
    pthread_exit(NULL);
    /* USER CODE REQUEST TEST END END */
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~ Response handlers ~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* This module does not implement any response handlers. */

//~~~~~~~~~~~~~~~~~~~~~~~~~~~ User functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~//

/* USER CODE MODULE FUNCTIONS BEGIN */
/* USER CODE MODULE FUNCTIONS END */

